import type { Locale } from "@/types/academy";

type Pair = readonly [fr: string, ar: string];

const copy: Record<string, Pair> = {
  "Your German journey continues.": ["Votre parcours en allemand continue.", "تستمر رحلتك في تعلّم الألمانية."],
  "Current level": ["Niveau actuel", "المستوى الحالي"],
  "Intermediate German": ["Allemand intermédiaire", "الألمانية المتوسطة"],
  "You have built a strong everyday foundation. Your next chapter is confident workplace conversation.": ["Vous avez acquis de solides bases au quotidien. Votre prochaine étape : communiquer avec assurance au travail.", "لقد بنيت أساساً قوياً للاستخدام اليومي. خطوتك التالية هي التواصل بثقة في العمل."],
  "Continue learning": ["Continuer à apprendre", "متابعة التعلّم"],
  "View progress": ["Voir la progression", "عرض التقدّم"],
  "Next lesson": ["Prochaine leçon", "الدرس القادم"],
  "German for real-world conversations.": ["L’allemand pour les conversations du quotidien.", "الألمانية للمحادثات الواقعية."],
  "Today": ["Aujourd’hui", "اليوم"],
  "Monday, 14 September": ["Lundi 14 septembre", "الاثنين 14 سبتمبر"],
  "Live class": ["Cours en direct", "درس مباشر"],
  "Vocabulary practice": ["Pratique du vocabulaire", "تدريب المفردات"],
  "Workplace expressions": ["Expressions professionnelles", "عبارات مهنية"],
  "Due tomorrow": ["À rendre demain", "موعد التسليم غداً"],
  "Homework": ["Devoir", "واجب"],
  "Write a professional email": ["Rédiger un e-mail professionnel", "كتابة بريد إلكتروني مهني"],
  "Next milestone": ["Prochaine étape", "المحطة القادمة"],
  "Prepare for exam": ["Préparer l’examen", "الاستعداد للامتحان"],
  "Learning momentum": ["Dynamique d’apprentissage", "وتيرة التعلّم"],
  "A steady week of practice.": ["Une semaine de pratique régulière.", "أسبوع منتظم من التدريب."],
  "this week": ["cette semaine", "هذا الأسبوع"],
  "Skill balance": ["Équilibre des compétences", "توازن المهارات"],
  "Your strongest edge is reading.": ["Votre point fort est la lecture.", "القراءة هي نقطة قوتك."],
  "Small steps. Real fluency.": ["De petits pas. Une vraie aisance.", "خطوات صغيرة. طلاقة حقيقية."],
  "Continue where you left off in Arbeit · Im Büro.": ["Reprenez là où vous vous êtes arrêté dans Arbeit · Im Büro.", "تابع من حيث توقفت في Arbeit · Im Büro."],
  "Continue your journey": ["Poursuivre votre parcours", "تابع رحلتك"],
  "A2 — German Intermediate": ["A2 — Allemand intermédiaire", "A2 — الألمانية المتوسطة"],
  "Build confidence for everyday life, work and travel.": ["Gagnez en assurance au quotidien, au travail et en voyage.", "اكتسب الثقة في الحياة اليومية والعمل والسفر."],
  "Subscription required": ["Abonnement requis", "الاشتراك مطلوب"],
  "Your learning access is currently paused.": ["Votre accès à l’apprentissage est momentanément suspendu.", "تم إيقاف وصولك إلى التعلّم مؤقتاً."],
  "Course materials, live classes and mock exams are temporarily unavailable.": ["Les ressources, cours en direct et examens blancs sont temporairement indisponibles.", "الموارد والدروس المباشرة والامتحانات التجريبية غير متاحة مؤقتاً."],
  "Renew access": ["Réactiver l’accès", "تجديد الوصول"],
  "Course progress": ["Progression du cours", "تقدّم الدورة"],
  "lessons complete": ["leçons terminées", "دروس مكتملة"],
  "Learning time": ["Temps d’apprentissage", "وقت التعلّم"],
  "estimated remaining": ["restantes estimées", "متبقية تقديرياً"],
  "Mock Exam": ["Examen blanc", "امتحان تجريبي"],
  "ready": ["prêt", "جاهز"],
  "lessons": ["leçons", "دروس"],
  "exercises": ["exercices", "تمارين"],
  "estimated": ["estimées", "تقديرية"],
  "Locked": ["Verrouillé", "مقفل"],
  "Completed": ["Terminé", "مكتمل"],
  "In progress": ["En cours", "قيد التقدّم"],
  "Available": ["Disponible", "متاح"],
  "Lesson 04 / 07": ["Leçon 04 / 07", "الدرس 04 / 07"],
  "Vocabulary": ["Vocabulaire", "المفردات"],
  "Grammar": ["Grammaire", "القواعد"],
  "Listening": ["Compréhension orale", "الاستماع"],
  "Practice": ["Pratique", "التدريب"],
  "Useful language for the workplace.": ["Le vocabulaire utile au travail.", "لغة مفيدة في بيئة العمل."],
  "What you’ll learn": ["Ce que vous apprendrez", "ما ستتعلمه"],
  "Workplace vocabulary": ["Vocabulaire professionnel", "مفردات العمل"],
  "Useful expressions": ["Expressions utiles", "عبارات مفيدة"],
  "Dative prepositions": ["Prépositions avec le datif", "حروف الجر مع حالة الداتيف"],
  "Natural pronunciation": ["Prononciation naturelle", "النطق الطبيعي"],
  "Lesson progress": ["Progression de la leçon", "تقدّم الدرس"],
  "Continue lesson": ["Continuer la leçon", "متابعة الدرس"],
  "Your result": ["Votre résultat", "نتيجتك"],
  "Good progress.": ["Bonne progression.", "تقدّم جيد."],
  "Keep practicing.": ["Continuez à vous entraîner.", "واصل التدريب."],
  "Performance by skill": ["Résultats par compétence", "الأداء حسب المهارة"],
  "Your strengths": ["Vos points forts", "نقاط قوتك"],
  "Your focus area": ["Votre priorité", "مجال التركيز"],
  "Reading comprehension and identifying key information.": ["Compréhension écrite et repérage des informations clés.", "فهم المقروء وتحديد المعلومات الأساسية."],
  "Sentence structure and connectors in written German.": ["Structure des phrases et connecteurs à l’écrit.", "بنية الجملة والروابط في الألمانية المكتوبة."],
  "Exit exam": ["Quitter l’examen", "الخروج من الامتحان"],
  "Question": ["Question", "السؤال"],
  "Listen and choose one answer": ["Écoutez et choisissez une réponse", "استمع واختر إجابة واحدة"],
  "Previous": ["Précédent", "السابق"],
  "Next": ["Suivant", "التالي"],
  "Scoring…": ["Calcul du résultat…", "جارٍ حساب النتيجة…"],
  "Finish exam": ["Terminer l’examen", "إنهاء الامتحان"],
  "Prüfungen": ["Examens", "الامتحانات"],
  "A clear path from foundation to independent German.": ["Un parcours clair des bases vers l’autonomie en allemand.", "مسار واضح من الأساسيات إلى الاستقلالية في الألمانية."],
  "Current": ["Actuel", "الحالي"],
  "Waiting": ["En attente", "قيد الانتظار"],
  "Final Assessment": ["Évaluation finale", "التقييم النهائي"],
  "Complete 80% of A2 to unlock": ["Terminez 80 % du niveau A2 pour le débloquer", "أكمل 80٪ من مستوى A2 لفتحه"],
  "Start exam": ["Commencer l’examen", "بدء الامتحان"],
  "View readiness": ["Voir la préparation", "عرض الجاهزية"],
  "Good morning, Anna.": ["Bonjour, Anna.", "صباح الخير، آنا."],
  "Your teaching day, clearly arranged.": ["Votre journée d’enseignement, clairement organisée.", "يومك التدريسي منظم بوضوح."],
  "Monday": ["Lundi", "الاثنين"],
  "14 September": ["14 septembre", "14 سبتمبر"],
  "classes": ["classes", "حصص"],
  "Your next class begins in 42 minutes.": ["Votre prochain cours commence dans 42 minutes.", "يبدأ درسك القادم خلال 42 دقيقة."],
  "Open schedule": ["Voir le planning", "عرض الجدول"],
  "Room 3": ["Salle 3", "القاعة 3"],
  "Room 2": ["Salle 2", "القاعة 2"],
  "Online": ["En ligne", "عن بُعد"],
  "Assignments": ["Devoirs", "الواجبات"],
  "waiting for review": ["à corriger", "بانتظار المراجعة"],
  "Students": ["Étudiants", "الطلاب"],
  "across three classes": ["dans trois classes", "ضمن ثلاثة فصول"],
  "Attendance": ["Présence", "الحضور"],
  "this month": ["ce mois-ci", "هذا الشهر"],
  "Students requiring attention": ["Étudiants à accompagner", "طلاب يحتاجون إلى متابعة"],
  "Recent submissions": ["Travaux récents", "التسليمات الأخيرة"],
  "Overview": ["Vue d’ensemble", "نظرة عامة"],
  "The academy is growing steadily this month.": ["L’académie progresse régulièrement ce mois-ci.", "تشهد الأكاديمية نمواً ثابتاً هذا الشهر."],
  "Revenue": ["Revenus", "الإيرادات"],
  "Learning performance": ["Performance pédagogique", "الأداء التعليمي"],
  "Active classes": ["Classes actives", "الفصول النشطة"],
  "stable": ["stable", "مستقر"],
  "Revenue trend": ["Évolution des revenus", "اتجاه الإيرادات"],
  "Healthy, predictable growth.": ["Une croissance saine et prévisible.", "نمو صحي ويمكن توقّعه."],
  "Level distribution": ["Répartition par niveau", "توزيع المستويات"],
  "Recent activity": ["Activité récente", "النشاط الأخير"],
  "Enrollment": ["Inscriptions", "التسجيل"],
  "Academics": ["Pédagogie", "التعليم"],
  "Finance": ["Finances", "المالية"],
  "Contact student": ["Contacter l’étudiant", "التواصل مع الطالب"],
  "Learning": ["Apprentissage", "التعلّم"],
  "Payments": ["Paiements", "المدفوعات"],
  "Learning progress": ["Progression pédagogique", "التقدّم التعليمي"],
  "Foundations": ["Fondamentaux", "الأساسيات"],
  "Intermediate": ["Intermédiaire", "متوسط"],
  "Independent": ["Autonome", "مستقل"],
  "Advanced": ["Avancé", "متقدم"],
  "average": ["moyenne", "المعدل"],
  "attendance": ["présence", "الحضور"],
  "progress": ["progression", "التقدّم"],
  "Payment status": ["État du paiement", "حالة الدفع"],
  "Teacher": ["Professeur", "الأستاذ"],
  "Yesterday": ["Hier", "أمس"],
  "Your program": ["Votre programme", "برنامجك"],
  "A clear view of your subscription and payment history.": ["Une vue claire de votre abonnement et de vos paiements.", "نظرة واضحة على اشتراكك وسجل مدفوعاتك."],
  "A2 program": ["Programme A2", "برنامج A2"],
  "/ month": ["/ mois", "/ الشهر"],
  "Next payment": ["Prochain paiement", "الدفعة القادمة"],
  "Learning access": ["Accès aux cours", "الوصول إلى التعلّم"],
  "Full access": ["Accès complet", "وصول كامل"],
  "Paused": ["Suspendu", "متوقف"],
  "Subscription timeline": ["Historique de l’abonnement", "المسار الزمني للاشتراك"],
  "Program started": ["Début du programme", "بداية البرنامج"],
  "Payment confirmed": ["Paiement confirmé", "تم تأكيد الدفع"],
  "Next renewal": ["Prochain renouvellement", "التجديد القادم"],
  "Payment history": ["Historique des paiements", "سجل المدفوعات"],
  "Paid": ["Payé", "مدفوع"],
  "Edit profile": ["Modifier le profil", "تعديل الملف الشخصي"],
  "Learning statistics": ["Statistiques d’apprentissage", "إحصاءات التعلّم"],
  "Current streak": ["Série actuelle", "السلسلة الحالية"],
  "Lessons completed": ["Leçons terminées", "الدروس المكتملة"],
  "Mock exams": ["Examens blancs", "الامتحانات التجريبية"],
  "Learning timeline": ["Parcours d’apprentissage", "المسار التعليمي"],
  "Materials": ["Ressources", "الموارد"],
  "Learning resources for every part of your course.": ["Des ressources pour chaque étape de votre parcours.", "موارد لكل مرحلة من دورتك."],
  "All": ["Tout", "الكل"],
  "Exercise": ["Exercice", "تمرين"],
  "Open": ["Ouvrir", "فتح"],
  "Live Classes": ["Cours en direct", "الدروس المباشرة"],
  "Join your scheduled virtual classroom.": ["Rejoignez votre classe virtuelle programmée.", "انضم إلى فصلك الافتراضي المجدول."],
  "Today's classes": ["Cours du jour", "دروس اليوم"],
  "Starting soon": ["Commence bientôt", "سيبدأ قريباً"],
  "Join class": ["Rejoindre le cours", "الانضمام إلى الدرس"],
  "Class chat": ["Discussion du cours", "محادثة الدرس"],
  "Leave meeting": ["Quitter le cours", "مغادرة الدرس"],
  "Calendar": ["Calendrier", "التقويم"],
  "Your classes, exams and deadlines for September 2026.": ["Vos cours, examens et échéances de septembre 2026.", "دروسك وامتحاناتك ومواعيدك لشهر سبتمبر 2026."],
  "Week": ["Semaine", "أسبوع"],
  "Month": ["Mois", "شهر"],
  "Instructions": ["Consignes", "التعليمات"],
  "Attached files": ["Fichiers joints", "الملفات المرفقة"],
  "Your submission": ["Votre travail", "تسليمك"],
  "Upload your work": ["Importer votre travail", "رفع عملك"],
  "Submit assignment": ["Envoyer le devoir", "إرسال الواجب"],
  "Track your homework, submissions and grades.": ["Suivez vos devoirs, travaux rendus et notes.", "تابع واجباتك وتسليماتك ودرجاتك."],
  "Deadline": ["Échéance", "الموعد النهائي"],
  "Status": ["Statut", "الحالة"],
  "Grade": ["Note", "الدرجة"],
  "View": ["Voir", "عرض"],
  "My Progress": ["Ma progression", "تقدّمي"],
  "A clear view of your learning momentum and next milestone.": ["Une vue claire de votre rythme et de votre prochaine étape.", "نظرة واضحة على وتيرة تعلّمك ومحطتك القادمة."],
  "Monthly progress": ["Progression mensuelle", "التقدّم الشهري"],
  "Level journey": ["Parcours de niveau", "مسار المستوى"],
  "Target": ["Objectif", "الهدف"],
  "Messages": ["Messages", "الرسائل"],
  "Stay connected with teachers and administration.": ["Restez en contact avec les professeurs et l’administration.", "ابقَ على تواصل مع الأساتذة والإدارة."],
  "Administration": ["Administration", "الإدارة"],
  "Online": ["En ligne", "متصل"],
  "Write a message…": ["Écrire un message…", "اكتب رسالة…"],
};

const substitutions: Array<readonly [RegExp, Pair]> = [
  [/\bToday\b/g, ["Aujourd’hui", "اليوم"]],
  [/\bStudent\b/g, ["Étudiant", "طالب"]],
  [/\bstudents\b/gi, ["étudiants", "طلاب"]],
  [/\bSeptember\b/g, ["septembre", "سبتمبر"]],
  [/\bAugust\b/g, ["août", "أغسطس"]],
  [/\bJuly\b/g, ["juillet", "يوليو"]],
  [/\bMarch\b/g, ["mars", "مارس"]],
  [/\bActive\b/g, ["Actif", "نشط"]],
  [/\bPublished\b/g, ["Publié", "منشور"]],
  [/\bDraft\b/g, ["Brouillon", "مسودة"]],
  [/\bminutes\b/g, ["minutes", "دقائق"]],
  [/\bhours\b/g, ["heures", "ساعات"]],
];

export function localizeInterfaceText(value: string, locale: Locale) {
  const trimmed = value.trim();
  if (!trimmed) return value;
  const exact = copy[trimmed];
  let translated = exact ? exact[locale === "ar" ? 1 : 0] : trimmed;
  if (!exact) {
    for (const [pattern, pair] of substitutions) {
      translated = translated.replace(pattern, pair[locale === "ar" ? 1 : 0]);
    }
  }
  return value.replace(trimmed, translated);
}
