import type { Locale } from "@/types/academy";
import { translateKnownValue } from "@/lib/i18n";

type Pair = readonly [fr: string, ar: string];

const copy: Record<string, Pair> = {
  "Hallo, Ahmed.": ["Bonjour, Ahmed.", "مرحباً، أحمد."],
  "Your German journey continues.": [
    "Votre parcours en allemand continue.",
    "تستمر رحلتك في تعلّم الألمانية.",
  ],
  "Current level": ["Niveau actuel", "المستوى الحالي"],
  "Intermediate German": ["Allemand intermédiaire", "الألمانية المتوسطة"],
  complete: ["terminé", "مكتمل"],
  "You have built a strong everyday foundation. Your next chapter is confident workplace conversation.":
    [
      "Vous avez acquis de solides bases au quotidien. Votre prochaine étape : communiquer avec assurance au travail.",
      "لقد بنيت أساساً قوياً للاستخدام اليومي. خطوتك التالية هي التواصل بثقة في العمل.",
    ],
  "Continue learning": ["Continuer à apprendre", "متابعة التعلّم"],
  "View progress": ["Voir la progression", "عرض التقدّم"],
  "Next lesson": ["Prochaine leçon", "الدرس القادم"],
  "German for real-world conversations.": [
    "L’allemand pour les conversations du quotidien.",
    "الألمانية للمحادثات الواقعية.",
  ],
  Today: ["Aujourd’hui", "اليوم"],
  "Monday, 14 September": ["Lundi 14 septembre", "الاثنين 14 سبتمبر"],
  "Live class": ["Cours en direct", "درس مباشر"],
  "Vocabulary practice": ["Pratique du vocabulaire", "تدريب المفردات"],
  "Workplace expressions": ["Expressions professionnelles", "عبارات مهنية"],
  "Due tomorrow": ["À rendre demain", "موعد التسليم غداً"],
  Homework: ["Devoir", "واجب"],
  "Write a professional email": ["Rédiger un e-mail professionnel", "كتابة بريد إلكتروني مهني"],
  "Next milestone": ["Prochaine étape", "المحطة القادمة"],
  "A2 Mock Exam": ["Examen blanc A2", "امتحان A2 التجريبي"],
  "You are ready in Lesen and Hören. Focus next on written expression.": [
    "Vous êtes prêt en lecture et en compréhension orale. Concentrez-vous maintenant sur l’expression écrite.",
    "أنت مستعد في القراءة والاستماع. ركّز الآن على التعبير الكتابي.",
  ],
  "Prepare for exam": ["Préparer l’examen", "الاستعداد للامتحان"],
  "Learning momentum": ["Dynamique d’apprentissage", "وتيرة التعلّم"],
  "A steady week of practice.": ["Une semaine de pratique régulière.", "أسبوع منتظم من التدريب."],
  "this week": ["cette semaine", "هذا الأسبوع"],
  "Skill balance": ["Équilibre des compétences", "توازن المهارات"],
  "Your strongest edge is reading.": ["Votre point fort est la lecture.", "القراءة هي نقطة قوتك."],
  "Small steps. Real fluency.": ["De petits pas. Une vraie aisance.", "خطوات صغيرة. طلاقة حقيقية."],
  "Continue where you left off in Arbeit · Im Büro.": [
    "Reprenez là où vous vous êtes arrêté dans Arbeit · Im Büro.",
    "تابع من حيث توقفت في Arbeit · Im Büro.",
  ],
  "Continue your journey": ["Poursuivre votre parcours", "تابع رحلتك"],
  "A2 — German Intermediate": ["A2 — Allemand intermédiaire", "A2 — الألمانية المتوسطة"],
  "Build confidence for everyday life, work and travel.": [
    "Gagnez en assurance au quotidien, au travail et en voyage.",
    "اكتسب الثقة في الحياة اليومية والعمل والسفر.",
  ],
  "Subscription required": ["Abonnement requis", "الاشتراك مطلوب"],
  "Your learning access is currently paused.": [
    "Votre accès à l’apprentissage est momentanément suspendu.",
    "تم إيقاف وصولك إلى التعلّم مؤقتاً.",
  ],
  "Course materials, live classes and mock exams are temporarily unavailable.": [
    "Les ressources, cours en direct et examens blancs sont temporairement indisponibles.",
    "الموارد والدروس المباشرة والامتحانات التجريبية غير متاحة مؤقتاً.",
  ],
  "Renew access": ["Réactiver l’accès", "تجديد الوصول"],
  "Course progress": ["Progression du cours", "تقدّم الدورة"],
  "lessons complete": ["leçons terminées", "دروس مكتملة"],
  "Learning time": ["Temps d’apprentissage", "وقت التعلّم"],
  "estimated remaining": ["restantes estimées", "متبقية تقديرياً"],
  "Mock Exam": ["Examen blanc", "امتحان تجريبي"],
  ready: ["prêt", "جاهز"],
  lessons: ["leçons", "دروس"],
  exercises: ["exercices", "تمارين"],
  estimated: ["estimées", "تقديرية"],
  Locked: ["Verrouillé", "مقفل"],
  Completed: ["Terminé", "مكتمل"],
  "In progress": ["En cours", "قيد التقدّم"],
  Available: ["Disponible", "متاح"],
  "Lesson 04 / 07": ["Leçon 04 / 07", "الدرس 04 / 07"],
  Vocabulary: ["Vocabulaire", "المفردات"],
  Grammar: ["Grammaire", "القواعد"],
  Listening: ["Compréhension orale", "الاستماع"],
  Practice: ["Pratique", "التدريب"],
  "Useful language for the workplace.": [
    "Le vocabulaire utile au travail.",
    "لغة مفيدة في بيئة العمل.",
  ],
  "What you’ll learn": ["Ce que vous apprendrez", "ما ستتعلمه"],
  "Workplace vocabulary": ["Vocabulaire professionnel", "مفردات العمل"],
  "Useful expressions": ["Expressions utiles", "عبارات مفيدة"],
  "Dative prepositions": ["Prépositions avec le datif", "حروف الجر مع حالة الداتيف"],
  "Natural pronunciation": ["Prononciation naturelle", "النطق الطبيعي"],
  "Lesson progress": ["Progression de la leçon", "تقدّم الدرس"],
  "Continue lesson": ["Continuer la leçon", "متابعة الدرس"],
  "Your result": ["Votre résultat", "نتيجتك"],
  "Good progress.": ["Bonne progression.", "تقدّم جيد."],
  "Keep practicing.": ["Continuez à vous entraîner.", "واصل التدريب."],
  "Performance by skill": ["Résultats par compétence", "الأداء حسب المهارة"],
  "Your strengths": ["Vos points forts", "نقاط قوتك"],
  "Your focus area": ["Votre priorité", "مجال التركيز"],
  "Reading comprehension and identifying key information.": [
    "Compréhension écrite et repérage des informations clés.",
    "فهم المقروء وتحديد المعلومات الأساسية.",
  ],
  "Sentence structure and connectors in written German.": [
    "Structure des phrases et connecteurs à l’écrit.",
    "بنية الجملة والروابط في الألمانية المكتوبة.",
  ],
  "Exit exam": ["Quitter l’examen", "الخروج من الامتحان"],
  Question: ["Question", "السؤال"],
  "Listen and choose one answer": ["Écoutez et choisissez une réponse", "استمع واختر إجابة واحدة"],
  Previous: ["Précédent", "السابق"],
  Next: ["Suivant", "التالي"],
  "Scoring…": ["Calcul du résultat…", "جارٍ حساب النتيجة…"],
  "Finish exam": ["Terminer l’examen", "إنهاء الامتحان"],
  Prüfungen: ["Examens", "الامتحانات"],
  "A clear path from foundation to independent German.": [
    "Un parcours clair des bases vers l’autonomie en allemand.",
    "مسار واضح من الأساسيات إلى الاستقلالية في الألمانية.",
  ],
  Current: ["Actuel", "الحالي"],
  Waiting: ["En attente", "قيد الانتظار"],
  "Final Assessment": ["Évaluation finale", "التقييم النهائي"],
  "Complete 80% of A2 to unlock": [
    "Terminez 80 % du niveau A2 pour le débloquer",
    "أكمل 80٪ من مستوى A2 لفتحه",
  ],
  "Start exam": ["Commencer l’examen", "بدء الامتحان"],
  "View readiness": ["Voir la préparation", "عرض الجاهزية"],
  "Good morning, Anna.": ["Bonjour, Anna.", "صباح الخير، آنا."],
  "Your teaching day, clearly arranged.": [
    "Votre journée d’enseignement, clairement organisée.",
    "يومك التدريسي منظم بوضوح.",
  ],
  Monday: ["Lundi", "الاثنين"],
  "14 September": ["14 septembre", "14 سبتمبر"],
  classes: ["classes", "حصص"],
  "Your next class begins in 42 minutes.": [
    "Votre prochain cours commence dans 42 minutes.",
    "يبدأ درسك القادم خلال 42 دقيقة.",
  ],
  "Open schedule": ["Voir le planning", "عرض الجدول"],
  "Room 3": ["Salle 3", "القاعة 3"],
  "Room 2": ["Salle 2", "القاعة 2"],
  Online: ["En ligne", "متصل"],
  Assignments: ["Devoirs", "الواجبات"],
  "waiting for review": ["à corriger", "بانتظار المراجعة"],
  Students: ["Étudiants", "الطلاب"],
  "across three classes": ["dans trois classes", "ضمن ثلاثة فصول"],
  Attendance: ["Présence", "الحضور"],
  "this month": ["ce mois-ci", "هذا الشهر"],
  "Students requiring attention": ["Étudiants à accompagner", "طلاب يحتاجون إلى متابعة"],
  "Recent submissions": ["Travaux récents", "التسليمات الأخيرة"],
  Overview: ["Vue d’ensemble", "نظرة عامة"],
  "The academy is growing steadily this month.": [
    "L’académie progresse régulièrement ce mois-ci.",
    "تشهد الأكاديمية نمواً ثابتاً هذا الشهر.",
  ],
  Revenue: ["Revenus", "الإيرادات"],
  "Learning performance": ["Performance pédagogique", "الأداء التعليمي"],
  "Active classes": ["Classes actives", "الفصول النشطة"],
  stable: ["stable", "مستقر"],
  "Revenue trend": ["Évolution des revenus", "اتجاه الإيرادات"],
  "Healthy, predictable growth.": ["Une croissance saine et prévisible.", "نمو صحي ويمكن توقّعه."],
  "Level distribution": ["Répartition par niveau", "توزيع المستويات"],
  "Recent activity": ["Activité récente", "النشاط الأخير"],
  Enrollment: ["Inscriptions", "التسجيل"],
  Academics: ["Pédagogie", "التعليم"],
  Finance: ["Finances", "المالية"],
  "Contact student": ["Contacter l’étudiant", "التواصل مع الطالب"],
  Learning: ["Apprentissage", "التعلّم"],
  Payments: ["Paiements", "المدفوعات"],
  "Learning progress": ["Progression pédagogique", "التقدّم التعليمي"],
  Foundations: ["Fondamentaux", "الأساسيات"],
  Intermediate: ["Intermédiaire", "متوسط"],
  Independent: ["Autonome", "مستقل"],
  Advanced: ["Avancé", "متقدم"],
  average: ["moyenne", "المعدل"],
  attendance: ["présence", "الحضور"],
  progress: ["progression", "التقدّم"],
  "Payment status": ["État du paiement", "حالة الدفع"],
  Teacher: ["Professeur", "الأستاذ"],
  Yesterday: ["Hier", "أمس"],
  "Your program": ["Votre programme", "برنامجك"],
  "A clear view of your subscription and payment history.": [
    "Une vue claire de votre abonnement et de vos paiements.",
    "نظرة واضحة على اشتراكك وسجل مدفوعاتك.",
  ],
  "A2 program": ["Programme A2", "برنامج A2"],
  "/ month": ["/ mois", "/ الشهر"],
  "Next payment": ["Prochain paiement", "الدفعة القادمة"],
  "Learning access": ["Accès aux cours", "الوصول إلى التعلّم"],
  "Full access": ["Accès complet", "وصول كامل"],
  Paused: ["Suspendu", "متوقف"],
  "Subscription timeline": ["Historique de l’abonnement", "المسار الزمني للاشتراك"],
  "Program started": ["Début du programme", "بداية البرنامج"],
  "Payment confirmed": ["Paiement confirmé", "تم تأكيد الدفع"],
  "Next renewal": ["Prochain renouvellement", "التجديد القادم"],
  "Payment history": ["Historique des paiements", "سجل المدفوعات"],
  Paid: ["Payé", "مدفوع"],
  "Edit profile": ["Modifier le profil", "تعديل الملف الشخصي"],
  "Learning statistics": ["Statistiques d’apprentissage", "إحصاءات التعلّم"],
  "Current streak": ["Série actuelle", "السلسلة الحالية"],
  "Lessons completed": ["Leçons terminées", "الدروس المكتملة"],
  "Mock exams": ["Examens blancs", "الامتحانات التجريبية"],
  "Learning timeline": ["Parcours d’apprentissage", "المسار التعليمي"],
  Materials: ["Ressources", "الموارد"],
  "Learning resources for every part of your course.": [
    "Des ressources pour chaque étape de votre parcours.",
    "موارد لكل مرحلة من دورتك.",
  ],
  All: ["Tout", "الكل"],
  Exercise: ["Exercice", "تمرين"],
  Open: ["Ouvrir", "فتح"],
  "Live Classes": ["Cours en direct", "الدروس المباشرة"],
  "Join your scheduled virtual classroom.": [
    "Rejoignez votre classe virtuelle programmée.",
    "انضم إلى فصلك الافتراضي المجدول.",
  ],
  "Today's classes": ["Cours du jour", "دروس اليوم"],
  "Starting soon": ["Commence bientôt", "سيبدأ قريباً"],
  "Join class": ["Rejoindre le cours", "الانضمام إلى الدرس"],
  "Class chat": ["Discussion du cours", "محادثة الدرس"],
  "Leave meeting": ["Quitter la réunion", "مغادرة الاجتماع"],
  Calendar: ["Calendrier", "التقويم"],
  "Your classes, exams and deadlines for September 2026.": [
    "Vos cours, examens et échéances de septembre 2026.",
    "دروسك وامتحاناتك ومواعيدك لشهر سبتمبر 2026.",
  ],
  Week: ["Semaine", "أسبوع"],
  Month: ["Mois", "شهر"],
  Instructions: ["Consignes", "التعليمات"],
  "Attached files": ["Fichiers joints", "الملفات المرفقة"],
  "Your submission": ["Votre travail", "تسليمك"],
  "Upload your work": ["Importer votre travail", "رفع عملك"],
  "Submit assignment": ["Envoyer le devoir", "إرسال الواجب"],
  "Track your homework, submissions and grades.": [
    "Suivez vos devoirs, travaux rendus et notes.",
    "تابع واجباتك وتسليماتك ودرجاتك.",
  ],
  Deadline: ["Échéance", "الموعد النهائي"],
  Status: ["Statut", "الحالة"],
  Grade: ["Note", "الدرجة"],
  View: ["Voir", "عرض"],
  "My Progress": ["Ma progression", "تقدّمي"],
  "A clear view of your learning momentum and next milestone.": [
    "Une vue claire de votre rythme et de votre prochaine étape.",
    "نظرة واضحة على وتيرة تعلّمك ومحطتك القادمة.",
  ],
  "Monthly progress": ["Progression mensuelle", "التقدّم الشهري"],
  "Level journey": ["Parcours de niveau", "مسار المستوى"],
  Target: ["Objectif", "الهدف"],
  Messages: ["Messages", "الرسائل"],
  "Stay connected with teachers and administration.": [
    "Restez en contact avec les professeurs et l’administration.",
    "ابقَ على تواصل مع الأساتذة والإدارة.",
  ],
  Administration: ["Administration", "الإدارة"],
  "Write a message…": ["Écrire un message…", "اكتب رسالة…"],
  "Live sessions": ["Sessions en direct", "الجلسات المباشرة"],
  "Create a class meeting and join the same Jitsi room from any authorized account.": [
    "Créez une réunion de classe et rejoignez la même salle Jitsi depuis tout compte autorisé.",
    "أنشئ اجتماع صف وانضم إلى نفس غرفة Jitsi من أي حساب مصرّح.",
  ],
  "No upcoming sessions": ["Aucune session à venir", "لا جلسات قادمة"],
  "Teachers or directors can create a live session for a class.": [
    "Les professeurs ou la direction peuvent créer une session pour une classe.",
    "يمكن للأساتذة أو الإدارة إنشاء جلسة لصف.",
  ],
  "Live now": ["En direct", "مباشر الآن"],
  Upcoming: ["À venir", "القادمة"],
  Past: ["Passées", "السابقة"],
  "No scheduled sessions.": ["Aucune session planifiée.", "لا جلسات مجدولة."],
  "Create session": ["Créer une session", "إنشاء جلسة"],
  Title: ["Titre", "العنوان"],
  "Select class": ["Choisir une classe", "اختر الصف"],
  Cancel: ["Annuler", "إلغاء"],
  "Create & join": ["Créer et rejoindre", "إنشاء والانضمام"],
  "Join meeting": ["Rejoindre la réunion", "الانضمام إلى الاجتماع"],
  "End session": ["Terminer la session", "إنهاء الجلسة"],
  "Access restricted": ["Accès restreint", "الوصول مقيد"],
  "Live classes require an active subscription. Open Payments to review your status.": [
    "Les cours en direct nécessitent un abonnement actif. Ouvrez Paiements pour vérifier votre statut.",
    "الدروس المباشرة تتطلب اشتراكاً نشطاً. افتح المدفوعات لمراجعة حالتك.",
  ],
  "Session unavailable": ["Session indisponible", "الجلسة غير متاحة"],
  "No meeting was selected.": ["Aucune réunion n’a été sélectionnée.", "لم يتم اختيار اجتماع."],
  "Back to sessions": ["Retour aux sessions", "العودة إلى الجلسات"],
  "Unable to join the meeting": [
    "Impossible de rejoindre la réunion",
    "تعذّر الانضمام إلى الاجتماع",
  ],
  "Session cancelled": ["Session annulée", "تم إلغاء الجلسة"],
  "Loading session…": ["Chargement de la session…", "جارٍ تحميل الجلسة…"],
  "Connecting to meeting room…": ["Connexion à la salle…", "جارٍ الاتصال بغرفة الاجتماع…"],
  Retry: ["Réessayer", "إعادة المحاولة"],
  Help: ["Aide", "مساعدة"],
  "Hide help": ["Masquer l’aide", "إخفاء المساعدة"],
  Classes: ["Classes", "الصفوف"],
  "Schedules, teachers and capacity across all levels.": [
    "Horaires, professeurs et capacités sur tous les niveaux.",
    "الجداول والأساتذة والسعة عبر جميع المستويات.",
  ],
  Teachers: ["Professeurs", "الأساتذة"],
  "Faculty overview and assigned classes.": [
    "Vue d’ensemble du corps enseignant et des classes assignées.",
    "نظرة عامة على الأساتذة والصفوف المعيّنة.",
  ],
  "Audit Logs": ["Journal d’audit", "سجل التدقيق"],
  "Traceable activity across the academy.": [
    "Activité traçable dans toute l’académie.",
    "نشاط يمكن تتبّعه عبر الأكاديمية.",
  ],
  Subscriptions: ["Abonnements", "الاشتراكات"],
  "Student subscription status from Supabase.": [
    "Statut des abonnements étudiants.",
    "حالة اشتراكات الطلاب.",
  ],
  "Payment Management": ["Gestion des paiements", "إدارة المدفوعات"],
  "Payments linked to subscriptions and academic access.": [
    "Paiements liés aux abonnements et à l’accès académique.",
    "مدفوعات مرتبطة بالاشتراكات والوصول الأكاديمي.",
  ],
  "No payments yet": ["Aucun paiement pour le moment", "لا مدفوعات بعد"],
  "Record a payment for a student to start the subscription workflow.": [
    "Enregistrez un paiement pour démarrer le workflow d’abonnement.",
    "سجّل دفعة لطالب لبدء مسار الاشتراك.",
  ],
  "Record payment": ["Enregistrer un paiement", "تسجيل دفعة"],
  "Mark paid": ["Marquer payé", "تعليميل كمدفوع"],
  "Mark overdue": ["Marquer en retard", "تعليميل كمتأخر"],
  "Access policy": ["Politique d’accès", "سياسة الوصول"],
  "Full academic access": ["Accès académique complet", "وصول أكاديمي كامل"],
  "Learning locked": ["Apprentissage verrouillé", "التعلّم مقفل"],
  "Select student": ["Choisir un étudiant", "اختر طالباً"],
  Amount: ["Montant", "المبلغ"],
  Create: ["Créer", "إنشاء"],
  "Subscription and payment history from your academy account.": [
    "Historique d’abonnement et de paiements de votre compte.",
    "سجل الاشتراك والمدفوعات من حسابك.",
  ],
  Subscription: ["Abonnement", "الاشتراك"],
  "Academic access restricted": ["Accès académique restreint", "الوصول الأكاديمي مقيد"],
  "Course Management": ["Gestion des cours", "إدارة الدورات"],
  "Curriculum structure across A1–B2 from Supabase.": [
    "Structure du curriculum de A1 à B2.",
    "هيكل المنهج من A1 إلى B2.",
  ],
  "Lesson Manager": ["Gestionnaire de leçons", "مدير الدروس"],
  "Create and publish lessons stored in Supabase.": [
    "Créer et publier des leçons.",
    "إنشاء ونشر الدروس.",
  ],
  "Private library files via Supabase Storage.": [
    "Fichiers de la bibliothèque privée.",
    "ملفات المكتبة الخاصة.",
  ],
  "Upload material": ["Importer un document", "رفع مادة"],
  "Upload to library": ["Envoyer vers la bibliothèque", "رفع إلى المكتبة"],
  "Library is empty": ["La bibliothèque est vide", "المكتبة فارغة"],
  "Upload a PDF, audio or video to get started.": [
    "Importez un PDF, un audio ou une vidéo pour commencer.",
    "ارفع ملف PDF أو صوت أو فيديو للبدء.",
  ],
  "My Courses": ["Mes cours", "دوراتي"],
  "Published curriculum from your academy.": [
    "Curriculum publié de votre académie.",
    "المنهج المنشور في أكاديميتك.",
  ],
  "An active subscription is required to open courses. Review your payments to renew.": [
    "Un abonnement actif est requis pour ouvrir les cours. Consultez vos paiements pour renouveler.",
    "يلزم اشتراك نشط لفتح الدورات. راجع مدفوعاتك للتجديد.",
  ],
  "Open payments": ["Ouvrir les paiements", "فتح المدفوعات"],
  "Publish real class assignments to Supabase.": [
    "Publiez de vrais devoirs de classe.",
    "انشر واجبات صف حقيقية.",
  ],
  "Academy-wide homework pipeline.": [
    "Pipeline des devoirs de l’académie.",
    "مسار واجبات الأكاديمية.",
  ],
  "Homework assigned to your classes.": [
    "Devoirs assignés à vos classes.",
    "واجبات مخصّصة لصفوفك.",
  ],
  Exams: ["Examens", "الامتحانات"],
  "Published mock exams for your level.": [
    "Examens blancs publiés pour votre niveau.",
    "امتحانات تجريبية منشورة لمستواك.",
  ],
  "Published mock exams for your level. Timer and scoring are server-backed.": [
    "Examens blancs pour votre niveau. Chrono et notation côté serveur.",
    "امتحانات تجريبية لمستواك. المؤقت والتصحيح من الخادم.",
  ],
  "Assessments available to your classes.": [
    "Évaluations disponibles pour vos classes.",
    "تقييمات متاحة لصفوفك.",
  ],
  "Exam Management": ["Gestion des examens", "إدارة الامتحانات"],
  "Create, publish and manage academy assessments.": [
    "Créer, publier et gérer les évaluations.",
    "إنشاء ونشر وإدارة التقييمات.",
  ],
  "An active subscription is required to take exams.": [
    "Un abonnement actif est requis pour passer les examens.",
    "يلزم اشتراك نشط لأداء الامتحانات.",
  ],
  "No exams available": ["Aucun examen disponible", "لا امتحانات متاحة"],
  "Published exams for your level will appear here.": [
    "Les examens publiés pour votre niveau apparaîtront ici.",
    "ستظهر هنا الامتحانات المنشورة لمستواك.",
  ],
  "No students found.": ["Aucun étudiant trouvé.", "لا طلاب."],
  "Search students…": ["Rechercher des étudiants…", "ابحث عن طلاب…"],
  "Enroll in class": ["Inscrire dans une classe", "التسجيل في صف"],
  "+ Create course": ["+ Créer un cours", "+ إنشاء دورة"],
  "+ Create class": ["+ Créer une classe", "+ إنشاء صف"],
  "+ Create session": ["+ Créer une session", "+ إنشاء جلسة"],
  "+ Record payment": ["+ Enregistrer un paiement", "+ تسجيل دفعة"],
  "Save attendance": ["Enregistrer les présences", "حفظ الحضور"],
  present: ["présent", "حاضر"],
  absent: ["absent", "غائب"],
  late: ["en retard", "متأخر"],
  excused: ["excusé", "معذور"],
  Present: ["Présent", "حاضر"],
  Absent: ["Absent", "غائب"],
  Late: ["En retard", "متأخر"],
  Excused: ["Excusé", "معذور"],
  "No enrolled students": ["Aucun étudiant inscrit", "لا طلاب مسجّلين"],
  "Enroll students in this class before taking attendance.": [
    "Inscrivez des étudiants dans cette classe avant de prendre les présences.",
    "سجّل طلاباً في هذا الصف قبل تسجيل الحضور.",
  ],
  "No notifications yet.": ["Aucune notification pour le moment.", "لا إشعارات بعد."],
  "Meeting created": ["Réunion créée", "تم إنشاء الاجتماع"],
  "Session created": ["Session créée", "تم إنشاء الجلسة"],
  "Session marked completed": ["Session marquée terminée", "تم تعليم الجلسة كمكتملة"],
  "Payment marked paid · subscription activated": [
    "Paiement marqué payé · abonnement activé",
    "تم تعليم الدفع كمدفوع · تم تفعيل الاشتراك",
  ],
  "Marked overdue · access restricted": [
    "Marqué en retard · accès restreint",
    "تم التعليم كمتأخر · الوصول مقيد",
  ],
  "Payment created": ["Paiement créé", "تم إنشاء الدفعة"],
  "Total amount": ["Montant total", "المبلغ الإجمالي"],
  Pending: ["En attente", "قيد الانتظار"],
  Overdue: ["En retard", "متأخر"],
  cancelled: ["annulé", "ملغى"],
  scheduled: ["planifié", "مجدول"],
  live: ["en direct", "مباشر"],
  completed: ["terminé", "مكتمل"],
  paid: ["payé", "مدفوع"],
  pending: ["en attente", "قيد الانتظار"],
  overdue: ["en retard", "متأخر"],
  "All statuses": ["Tous les statuts", "كل الحالات"],
  "Search student or reference…": [
    "Rechercher un étudiant ou une référence…",
    "ابحث عن طالب أو مرجع…",
  ],
  "No subscriptions": ["Aucun abonnement", "لا اشتراكات"],
  "Create a payment and mark it paid to activate a subscription.": [
    "Créez un paiement et marquez-le payé pour activer un abonnement.",
    "أنشئ دفعة وعلّمها كمدفوعة لتفعيل الاشتراك.",
  ],
  Starts: ["Début", "البداية"],
  Expires: ["Expiration", "الانتهاء"],
  Due: ["Échéance", "الاستحقاق"],
  "Paid on": ["Payé le", "تاريخ الدفع"],
  Method: ["Méthode", "الطريقة"],
  Actions: ["Actions", "إجراءات"],
  Level: ["Niveau", "المستوى"],
  Class: ["Classe", "الصف"],
  Progress: ["Progression", "التقدّم"],
  "Loading document…": ["Chargement du document…", "جارٍ تحميل المستند…"],
  Download: ["Télécharger", "تنزيل"],
  Close: ["Fermer", "إغلاق"],
  "Preview not available for this file type.": [
    "Aperçu indisponible pour ce type de fichier.",
    "المعاينة غير متاحة لهذا النوع من الملفات.",
  ],
  "Open in new tab": ["Ouvrir dans un nouvel onglet", "فتح في تبويب جديد"],
  Lesen: ["Lecture", "القراءة"],
  Hören: ["Écoute", "الاستماع"],
  Schreiben: ["Écriture", "الكتابة"],
  Sprechen: ["Expression orale", "المحادثة"],
  Grammatik: ["Grammaire", "القواعد"],
  Wortschatz: ["Vocabulaire", "المفردات"],
  Mock: ["Blanc", "تجريبي"],
  Official: ["Officiel", "رسمي"],
  "No classes assigned": ["Aucune classe assignée", "لا صفوف معيّنة"],
  "Search…": ["Rechercher…", "ابحث…"],
  "Create class": ["Créer une classe", "إنشاء صف"],
  "Create course": ["Créer un cours", "إنشاء دورة"],
  "Course title": ["Titre du cours", "عنوان الدورة"],
  "Select level": ["Choisir un niveau", "اختر المستوى"],
  "Level (optional)": ["Niveau (optionnel)", "المستوى (اختياري)"],
  "Session title": ["Titre de la session", "عنوان الجلسة"],
  "Start time": ["Heure de début", "وقت البداية"],
  "End time": ["Heure de fin", "وقت النهاية"],
  "Allow camera & microphone when the browser asks. Use Hang up inside Jitsi or Leave meeting above.":
    [
      "Autorisez la caméra et le micro lorsque le navigateur le demande. Utilisez Raccrocher dans Jitsi ou Quitter la réunion ci-dessus.",
      "اسمح بالكاميرا والميكروفون عندما يطلب المتصفح ذلك. استخدم إنهاء الاتصال داخل Jitsi أو مغادرة الاجتماع أعلاه.",
    ],
  "If audio/video is blocked: check the browser permission icon in the address bar. Both accounts must join the same room name on":
    [
      "Si l’audio/vidéo est bloqué : vérifiez l’icône d’autorisation dans la barre d’adresse. Les deux comptes doivent rejoindre le même nom de salle sur",
      "إذا حُجب الصوت/الفيديو: تحقق من أيقونة الأذونات في شريط العنوان. يجب أن ينضم الحسابان إلى نفس اسم الغرفة على",
    ],
  "Jitsi configuration missing.": ["Configuration Jitsi manquante.", "إعدادات Jitsi غير موجودة."],
  "Jitsi non configuré": ["Jitsi non configuré", "Jitsi غير مُعدّ"],
  "Real Account Required": ["Compte réel requis", "مطلوب حساب حقيقي"],
  "Compte réel requis": ["Compte réel requis", "مطلوب حساب حقيقي"],
  "Provider non configuré": ["Provider non configuré", "المزوّد غير مُعدّ"],
};

const substitutions: Array<readonly [RegExp, Pair]> = [
  [/\bToday\b/g, ["Aujourd’hui", "اليوم"]],
  [/\bStudent\b/g, ["Étudiant", "طالب"]],
  [/\bstudents\b/gi, ["étudiants", "طلاب"]],
  [/\bSeptember\b/g, ["septembre", "سبتمبر"]],
  [/\bAugust\b/g, ["août", "أغسطس"]],
  [/\bJuly\b/g, ["juillet", "يوليو"]],
  [/\bMarch\b/g, ["mars", "مارس"]],
  [/\bActive\b/g, ["Actif", "نشط"]],
  [/\bPublished\b/g, ["Publié", "منشور"]],
  [/\bDraft\b/g, ["Brouillon", "مسودة"]],
  [/\bminutes\b/g, ["minutes", "دقائق"]],
  [/\bhours\b/g, ["heures", "ساعات"]],
];

export function localizeInterfaceText(value: string, locale: Locale) {
  const trimmed = value.trim();
  if (!trimmed) return value;
  const exactEntry = Object.entries(copy).find(
    ([source, pair]) => source === trimmed || pair[0] === trimmed || pair[1] === trimmed,
  );
  const exact = exactEntry?.[1];
  let translated: string = exact
    ? (exact[locale === "ar" ? 1 : 0] ?? trimmed)
    : translateKnownValue(locale, trimmed);
  if (!exact) {
    for (const [pattern, pair] of substitutions) {
      translated = translated.replace(pattern, pair[locale === "ar" ? 1 : 0] ?? "");
    }
  }
  return value.replace(trimmed, translated);
}
