import { useState, type ReactNode } from "react";
import { Bell, BookOpen, CalendarDays, ChevronDown, ClipboardCheck, CreditCard, FileText, GraduationCap, LayoutDashboard, Library, LogOut, Menu, MessageSquare, Settings, ShieldCheck, UserRound, Users, Video, X, BarChart3, ReceiptText, ScrollText, Layers3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { notifications } from "@/data/mock-data";
import { useAcademy } from "./academy-context";

const menus = {
 student: [["dashboard","Dashboard",LayoutDashboard],["courses","My Courses",BookOpen],["calendar","Calendar",CalendarDays],["live","Live Classes",Video],["materials","Materials",Library],["assignments","Assignments",ClipboardCheck],["exams","Exams",FileText],["progress","My Progress",BarChart3],["payments","Payments",CreditCard],["messages","Messages",MessageSquare],["profile","Profile",UserRound]],
 teacher: [["dashboard","Dashboard",LayoutDashboard],["classes","My Classes",Users],["calendar","Calendar",CalendarDays],["lessons","Lessons",BookOpen],["materials","Materials",Library],["assignments","Assignments",ClipboardCheck],["exams","Exams",FileText],["attendance","Attendance",ShieldCheck],["messages","Messages",MessageSquare],["profile","Profile",UserRound]],
 director: [["dashboard","Dashboard",LayoutDashboard],["students","Students",Users],["teachers","Teachers",GraduationCap],["classes","Classes",Layers3],["courses","Courses",BookOpen],["levels","Levels",BarChart3],["materials","Materials",Library],["assignments","Assignments",ClipboardCheck],["exams","Exams",FileText],["payments","Payments",CreditCard],["subscriptions","Subscriptions",ShieldCheck],["invoices","Invoices",ReceiptText],["calendar","Calendar",CalendarDays],["messages","Messages",MessageSquare],["reports","Reports",BarChart3],["settings","Settings",Settings],["audit","Audit Logs",ScrollText]],
} as const;

export function AppShell({ children }: { children: ReactNode }) {
 const { role, page, navigate, setRole } = useAcademy(); const [mobile, setMobile] = useState(false); const [notice, setNotice] = useState(false);
 if (!role) return null; const name = role === "student" ? "Ahmed Benali" : role === "teacher" ? "Anna Müller" : "Samira El Mansouri";
 const sidebar = <><div className="flex h-17 items-center gap-3 border-b border-sidebar-border px-5"><span className="grid size-9 place-items-center rounded-lg bg-sidebar-primary text-sidebar-primary-foreground"><GraduationCap className="size-5" /></span><span><strong className="block font-display text-sm">Deutsch Academy</strong><small className="text-[10px] uppercase text-sidebar-foreground/50">Learning Center</small></span><button className="ml-auto lg:hidden" onClick={()=>setMobile(false)}><X className="size-5" /></button></div><nav className="flex-1 space-y-1 overflow-y-auto p-3">{menus[role].map(([id,label,Icon])=><button key={id} onClick={()=>{navigate(id);setMobile(false)}} className={`nav-item ${page===id?"nav-item-active":""}`}><Icon className="size-4"/><span>{label}</span>{id==="messages"&&<span className="ml-auto rounded-full bg-alert px-1.5 text-[10px] text-alert-foreground">3</span>}</button>)}</nav><div className="border-t border-sidebar-border p-3"><button className="nav-item" onClick={()=>setRole(null)}><LogOut className="size-4"/>Sign out</button></div></>;
 return <div className="min-h-screen bg-muted/35"><aside className="fixed inset-y-0 left-0 z-40 hidden w-64 flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground lg:flex">{sidebar}</aside>{mobile&&<div className="fixed inset-0 z-50 bg-foreground/30 lg:hidden" onClick={()=>setMobile(false)}><aside className="h-full w-72 bg-sidebar" onClick={e=>e.stopPropagation()}>{sidebar}</aside></div>}<div className="lg:pl-64"><header className="sticky top-0 z-30 flex h-17 items-center border-b bg-background/95 px-4 backdrop-blur sm:px-7"><button className="mr-3 lg:hidden" onClick={()=>setMobile(true)}><Menu className="size-5"/></button><div className="hidden text-sm text-muted-foreground sm:block">{role === "director" ? "Center management" : role === "teacher" ? "Teaching workspace" : "Learning workspace"}</div><div className="ml-auto flex items-center gap-2"><div className="relative"><Button size="icon" variant="ghost" aria-label="Notifications" onClick={()=>setNotice(!notice)}><Bell/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-alert"/></Button>{notice&&<div className="absolute right-0 top-11 w-[min(22rem,85vw)] rounded-lg border bg-popover p-2 shadow-card"><div className="px-3 py-2 text-sm font-semibold">Notifications</div>{notifications.map(n=><div key={n.id} className="flex gap-3 rounded-md px-3 py-2 hover:bg-accent"><span className={`mt-1.5 size-2 shrink-0 rounded-full ${n.unread?"bg-primary":"bg-border"}`}/><div><p className="text-sm">{n.title}</p><span className="text-xs text-muted-foreground">{n.time}</span></div></div>)}</div>}</div><button className="flex items-center gap-2 rounded-md p-1.5 hover:bg-accent"><span className="grid size-8 place-items-center rounded-full bg-secondary text-xs font-semibold text-primary">{name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span className="hidden text-left md:block"><strong className="block text-xs">{name}</strong><small className="capitalize text-muted-foreground">{role}</small></span><ChevronDown className="hidden size-3 md:block"/></button></div></header><main className="mx-auto max-w-[1500px] p-4 sm:p-7">{children}</main></div></div>;
}