import { useState, type ReactNode } from "react";
import { Bell, BookOpen, CalendarDays, ClipboardCheck, CreditCard, FileText, GraduationCap, Home, Library, LogOut, Menu, MessageSquare, Settings, ShieldCheck, UserRound, Users, Video, X, BarChart3, ReceiptText, ScrollText, Layers3 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { notifications } from "@/data/mock-data";
import { useAcademy } from "./academy-context";

const menus = {
 student: [["dashboard","Home",Home],["courses","Learning",BookOpen],["live","Live",Video],["assignments","Assignments",ClipboardCheck],["exams","Exams",FileText],["progress","Progress",BarChart3],["payments","Payments",CreditCard],["messages","Messages",MessageSquare],["profile","Profile",UserRound]],
 teacher: [["dashboard","Home",Home],["classes","My Classes",Users],["calendar","Calendar",CalendarDays],["lessons","Lessons",BookOpen],["materials","Materials",Library],["assignments","Assignments",ClipboardCheck],["exams","Exams",FileText],["attendance","Attendance",ShieldCheck],["messages","Messages",MessageSquare],["profile","Profile",UserRound]],
 director: [["dashboard","Overview",Home],["students","Students",Users],["teachers","Teachers",GraduationCap],["classes","Classes",Layers3],["courses","Courses",BookOpen],["levels","Levels",BarChart3],["materials","Materials",Library],["assignments","Assignments",ClipboardCheck],["exams","Exams",FileText],["payments","Payments",CreditCard],["subscriptions","Subscriptions",ShieldCheck],["invoices","Invoices",ReceiptText],["calendar","Calendar",CalendarDays],["messages","Messages",MessageSquare],["reports","Reports",BarChart3],["settings","Settings",Settings],["audit","Audit Logs",ScrollText]],
} as const;

export function AppShell({ children }: { children: ReactNode }) {
 const { role, page, navigate, setRole } = useAcademy(); const [mobile, setMobile] = useState(false); const [notice, setNotice] = useState(false);
 if (!role) return null; const name = role === "student" ? "Ahmed Benali" : role === "teacher" ? "Anna Schneider" : "Samira El Mansouri";
 const sidebar = <><div className="grid h-28 grid-cols-[minmax(0,1fr)_auto] items-center gap-3 border-b border-sidebar-border px-7"><div className="min-w-0"><strong className="block font-display text-lg font-normal leading-none">DEUTSCH</strong><span className="mt-1 block text-[10px] font-medium tracking-[0.22em] text-sidebar-foreground/45">ACADEMY</span></div><Button size="icon" variant="ghost" className="lg:hidden" onClick={()=>setMobile(false)} aria-label="Close navigation"><X className="size-5" /></Button></div><nav className="flex-1 overflow-y-auto px-4 py-6">{menus[role].map(([id,label,Icon],index)=><div key={id}>{((role==="student"&&index===6)||(role!=="student"&&[5,9,13].includes(index)))&&<div className="my-4 h-px bg-sidebar-border"/>}<button onClick={()=>{navigate(id);setMobile(false)}} className={`nav-item ${page===id?"nav-item-active":""}`}><Icon className="size-[17px]"/><span>{label}</span>{id==="messages"&&<span className="ml-auto size-1.5 rounded-full bg-alert"/>}</button></div>)}</nav><div className="border-t border-sidebar-border p-4"><button className="nav-item" onClick={()=>setRole(null)}><LogOut className="size-4"/>Sign out</button></div></>;
 return <div className="min-h-screen bg-background"><aside className="fixed inset-y-0 left-0 z-40 hidden w-60 flex-col border-r border-sidebar-border bg-sidebar text-sidebar-foreground lg:flex">{sidebar}</aside>{mobile&&<div className="fixed inset-0 z-50 bg-foreground/25 backdrop-blur-sm lg:hidden" onClick={()=>setMobile(false)}><aside className="flex h-full w-72 flex-col bg-sidebar shadow-card" onClick={e=>e.stopPropagation()}>{sidebar}</aside></div>}<div className="lg:pl-60"><header className="sticky top-0 z-30 grid h-20 grid-cols-[auto_minmax(0,1fr)_auto] items-center gap-3 border-b border-border bg-background/90 px-4 backdrop-blur-xl sm:px-8"><Button size="icon" variant="ghost" className="lg:hidden" onClick={()=>setMobile(true)} aria-label="Open navigation"><Menu className="size-5"/></Button><div className="hidden min-w-0 text-xs text-muted-foreground sm:block">{role === "director" ? "Academy administration" : role === "teacher" ? "Teaching studio" : "Monday · 14 September"}</div><div className="col-start-3 flex items-center gap-2"><div className="relative"><Button size="icon" variant="ghost" aria-label="Notifications" onClick={()=>setNotice(!notice)}><Bell/><span className="absolute right-2 top-2 size-1.5 rounded-full bg-alert"/></Button>{notice&&<div className="absolute right-0 top-12 w-[min(22rem,85vw)] rounded-xl border bg-popover p-2 shadow-card animate-scale-in"><div className="px-3 py-2 text-sm font-medium">Notifications</div>{notifications.map(n=><div key={n.id} className="flex gap-3 rounded-lg px-3 py-3 hover:bg-accent"><span className={`mt-1.5 size-1.5 shrink-0 rounded-full ${n.unread?"bg-primary":"bg-border"}`}/><div><p className="text-sm">{n.title}</p><span className="text-xs text-muted-foreground">{n.time}</span></div></div>)}</div>}</div><button className="flex items-center gap-3 rounded-lg p-1.5 transition hover:bg-accent"><span className="grid size-9 place-items-center rounded-full bg-secondary text-xs font-medium text-primary">{name.split(" ").map(x=>x[0]).join("").slice(0,2)}</span><span className="hidden text-left md:block"><strong className="block text-xs font-medium">{name}</strong><small className="capitalize text-muted-foreground">{role}</small></span></button></div></header><main className="mx-auto max-w-[1440px] p-5 sm:p-8 xl:p-12">{children}</main></div></div>;
}